"""
main.py

Kaggle submission entry point for the
Kaggriculture AI Agent.

Author: Jocelyn C. Dumlao
Project: Kaggriculture-AI-Agent
"""

from __future__ import annotations

from src.agent import KaggricultureAgent

# ==========================================================
# Create one persistent AI agent
# ==========================================================

agent_instance = KaggricultureAgent()


# ==========================================================
# Kaggle Entry Point
# ==========================================================

def agent(observation: dict) -> dict:
    """
    Main function called by Kaggle every game turn.

    Parameters
    ----------
    observation : dict
        Current game observation provided by Kaggle.

    Returns
    -------
    dict
        Action dictionary generated by the AI agent.
    """

    return agent_instance.act(observation)


# ==========================================================
# Optional Local Test
# ==========================================================

if __name__ == "__main__":

    print("Kaggriculture AI Agent")
    print("Submission entry point loaded successfully.")